# Generated by Django 2.2 on 2019-04-11 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('ID', models.CharField(max_length=200, unique=True)),
                ('Localizacion', models.CharField(max_length=200)),
                ('Despcricion', models.TextField(default='')),
                ('intervalo', models.IntegerField(default=15)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('Nombre_sensor', models.CharField(max_length=200)),
                ('ID_sensor', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Localizacion', models.CharField(max_length=200)),
                ('Despcricion', models.TextField()),
                ('intervalo', models.IntegerField(default=15)),
                ('tipo', models.CharField(max_length=200)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.Dispositivo')),
            ],
        ),
    ]
