# Generated by Django 2.2 on 2019-04-11 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valores',
            fields=[
                ('ID_valor', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ID_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
            ],
        ),
    ]
