// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "70518b5d-2cfe-415c-ae62-0f57bcec5fff");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1554882788);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1554882908);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1554901203);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1554882548);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1554882428);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1554882668);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1554883148);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1554883028);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1554882277);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7cbf2cae-e067-4c67-ae10-96715ecf5f76}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1554847200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1554902924043");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1554904712043");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1554901179372");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1554904779372");
user_pref("browser.search.region", "ES");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190327091201");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1554897575");
user_pref("browser.slowStartup.averageTime", 1826);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190327091201");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1554882280454");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "2cbc338595924d5db57f0193a2b470ff");
user_pref("extensions.blocklist.lastModified", "Tue, 09 Apr 2019 13:55:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1554882789);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190327091201");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{cc61606d-40dd-4f1c-876e-eb391d00db91}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"dc547faa-930d-47fe-ba0f-2e2d70ff0ab1\",\"screenshots@mozilla.org\":\"cefe4d39-9a16-42a1-87ec-6e416c42b3c5\",\"webcompat-reporter@mozilla.org\":\"33542411-5c23-42c1-a523-422eff6ae6cb\",\"webcompat@mozilla.org\":\"393b97c2-e4b8-4199-9664-7a4325272605\",\"fxmonitor@mozilla.org\":\"25ca1ac5-2bae-474a-854c-18fba26daf3f\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1554882937);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1554882401);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190327091201");
user_pref("media.gmp-manager.lastCheck", 1554882400);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1554882937);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4d631381-a18c-4547-b3ec-0d639de87cb7");
user_pref("security.sandbox.plugin.tempDirSuffix", "61e063c6-bd2f-498d-8d2c-b6fdf57bde12");
user_pref("services.blocklist.addons.checked", 1554882407);
user_pref("services.blocklist.gfx.checked", 1554882407);
user_pref("services.blocklist.onecrl.checked", 1554882407);
user_pref("services.blocklist.pinning.checked", 1554882407);
user_pref("services.blocklist.plugins.checked", 1554882407);
user_pref("services.settings.clock_skew_seconds", -52);
user_pref("services.settings.last_update_seconds", 1554882719);
user_pref("services.settings.main.language-dictionaries.last_check", 1554882407);
user_pref("services.settings.main.onboarding.last_check", 1554882407);
user_pref("services.settings.main.sites-classification.last_check", 1554882407);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1554882937);
user_pref("toolkit.startup.last_success", 1554897571);
user_pref("toolkit.telemetry.cachedClientID", "769f534a-506d-4f7a-bd28-740e9ec8f9ad");
user_pref("toolkit.telemetry.previousBuildID", "20190327091201");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
